name:                rust-to-rescript
version:             0.1.0.0
github:              "celsobonutti/rust-to-rescript"
license:             BSD3
author:              "Celso Bonutti"
maintainer:          "i.am@cel.so"
copyright:           "2021 Celso Bonutti"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/rust-to-rescript#readme>

dependencies:
  - base >= 4.7 && < 5
  - parser-combinators
  - hspec
  - protolude
  - text
  - containers
  - text
  - bytestring
  - megaparsec
  - transformers
  - file-embed

default-extensions:
  - NoImplicitPrelude
  - DisambiguateRecordFields
  - OverloadedStrings
  - NamedFieldPuns
  - DataKinds
  - DeriveGeneric
  - DerivingVia
  - FlexibleContexts
  - TypeApplications
  - DuplicateRecordFields

library:
  source-dirs: src

executables:
  rust-to-rescript-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rust-to-rescript

tests:
  rust-to-rescript-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rust-to-rescript
